#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ZXing.Mobile.Resource", IsApplication=false)]

namespace ZXing.Mobile
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int camera_swap_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int camera_swap_icon_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int flashlight_turn_off_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int flashlight_turn_off_icon_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int flashlight_turn_on_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int flashlight_turn_on_icon_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int ic_btn_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int ocr_turn_off_icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int ocr_turn_on_icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int scan_line_blue = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int scan_line_white = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public static int contentFrame = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int zxingscanneractivitylayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int zxingscannerfragmentlayout = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
	}
}
#pragma warning restore 1591
